### ISSUE TITLE
Access restriction bug on line transects

### ISSUE THREAD

**Issue by mikkohei13** [luomus/laji-api#12]
[line transect (ei-vakiolinjat) doesn't show a button](https://laji.fi/project/MHL.1/form/MHL.27/places?birdAssociationArea=all) to create new named places. Admins should be able to create new places.

Discussion: https://luomus-ict.slack.com/archives/C015154U19N/p1727781617315539

**Comment by olzraiti** [comment]
Fixed by 2c4a60f62ba5d79ef1b1837140bcaa11fb8391c9 and d4041fbb953c41b804c55b9fe931add56c9994d2

**Comment by olzraiti** [comment]
The fix wasn't enough, needs front side changes
