### ISSUE TITLE
Fix error triggered when saving a shared document

### ISSUE THREAD

**Issue by mikkohei13** [luomus/laji-api#43]
I guess that this is an API issue @olzraiti, please move/delegate if not.

## Repro:

1. Create a document on Vihko trip form
2. Add yourself and another user as observer
3. Give editor rights to both
4. Save the document
5. Login as the another user
6. Open the document
7. Save the document

### Expected:

- Saved normally

### Actual:

- Shows "Anteeksi, jokin meni pieleen"
- API at `https://laji.fi/api/documents/JX.1777485?personToken=` gives 404 Shared class "Document" has no method handling POST /JX.1777485?personToken=

**Comment by olzraiti** [comment]
@mikkohei13 it's in prod now (btw I'm not sure if you get a notification that this issues was completed - it means that the fix is in prod)

**Comment by mikkohei13** [comment]
Thanks, got it automatically as well.
