### ISSUE TITLE
Fix bug caused by conversion of values from string to boolean in /collections

### ISSUE THREAD

**Issue by wkmor1** [luomus/laji-api#44]
shareToGBIF property of a collection needs to be a string (a collection identifier Qname). But it is currently being converted to a boolean by the new API. 

This is breaking the finbif2gbif update service which assumes a Qname is returned https://github.com/luomus/finbif2gbif/blob/3e096450e531f4ec6cb352cb2a7c46bd1f739a09/R/get_collection_ids.R#L27

Blocking https://github.com/luomus/finbif2gbif/issues/1

**Comment by olzraiti** [comment]
closed by 95299a3
