### ISSUE TITLE
Filter fields in form's "excludeFromCopy" from prepopulated/accepted document when requesting named places

### ISSUE THREAD

**Issue by olzraiti** [luomus/laji-api#49]
Currently named places` prepopulatedDocument is returned as it is, the whole document. This is a security problem, allowing users to see documents they otherwise wouldn't be able to see.

This is to be fixed by filtering the prepopulatedDocument with the associated form's `excludeFromCopy`. It's a list of JSON paths for fields that should not be used in the document form when using the named place's `prepopulatedDocument`. This is currently done in front-end (https://github.com/luomus/laji/blob/b17d0d51afa6ba154aadf78b506302dd1c1b6ad3/projects/laji/src/app/%2Bproject-form/form/document-form/document-form.facade.ts#L443-L450)

**Comment by olzraiti** [comment]
I'll close this as wontfix after all, because:

* The units are already filtered by default from the `prepopulatedDocument`. If units are to be included, it has to be deliberately enabled with `MHL.includeUnits` option for the form. So security wise the situation isn't as bad as we though first.
* If the full document isn't in `prepopulatedDocument`, then if a user first fetches a named place and then saves it, the original `prepopulatedDocument` would be lost because it was saved with the filtered version.

**Comment by olzraiti** [comment]
FYI @esko-piirainen

**Comment by wkmor1** [comment]
@olzraiti FYI there is a little arrow next to close issue button where you can select "close as not planned"
